### PR TITLE
[issuer-api]: increase transaction log test consistency

### PR DESCRIPTION
**Pull request by soanvig**
I could not find the issue why it sometimes finds 3 certificates for given device-id. It fails randomly, and I couldn't reproduce this locally.

But my guess is that's some leftover from other test (like some transaction that was hanging on blockchain and it gets processed, and creates entries in database).

Because all tests in issuer-api where using the same device name, now tests in transaction logs are using different names (for each single test), so this should fix the issue while preserving tests usable.

### CODE REVIEW

**Comment by soanvig** [comment]
Do you know how can I restart deepscan?

**Comment by josipbagaric** [comment]
> Do you know how can I restart deepscan?

Not sure, but you can try rebasing the commit, or creating an empty commit with `git commit --allow-empty`. This should re-trigger the deepscan.

**Comment by soanvig** [comment]
> Not sure, but you can try rebasing the commit, or creating an empty commit with `git commit --allow-empty`. This should re-trigger the deepscan.

Oh yeah that helped

**Comment by soanvig** [comment]
Why the heck it shows 39 issues from not my changes

**Review by josipbagaric — APPROVED** [review]

**Review by JonaszJestem — APPROVED** [review]

**Pull request merged**
