### PR TITLE
chore/change license

### PR DESCRIPTION
**Pull request by alexworker23**
Change license of all packages from GPL-3 to MIT. 
Placed LICENSE file in the each package of the repo.

### CODE REVIEW

**Comment by josipbagaric** [comment]
@alexworker23 This is ready for a re-review? You addressed all the changes?

**Comment by alexworker23** [comment]
@JosephBagaric yes, added the license file for every package in the repo

**Comment by josipbagaric** [comment]
Depends on https://github.com/energywebfoundation/precise-proofs/pull/23 being merged and released?

**Comment by alexworker23** [comment]
@JosephBagaric Merged, published and deps version updated

**Review by josipbagaric — APPROVED** [review]
@alexworker23 Alright - released and updated Precise Proofs. Let's merge this 💪

**Pull request merged**
