### PR TITLE
feat/prep UI deploy

### PR DESCRIPTION
**Pull request by alexworker23**

### CODE REVIEW

**Review by josipbagaric — COMMENTED** [review]
Will this break the current deployment?

**Comment by alexworker23** [comment]
> Will this break the current deployment?

Well, it shouldn't, it will substitute it, when we finally merge it to master.
Or you want to add separate deployment for the new UI?

**Comment by JosephBagaric** [comment]
> > Will this break the current deployment?
> 
> Well, it shouldn't, it will substitute it, when we finally merge it to master.
> Or you want to add separate deployment for the new UI?

**Review by josipbagaric — APPROVED** [review]

**Comment by josipbagaric** [comment]
> > Will this break the current deployment?
> 
> Well, it shouldn't, it will substitute it, when we finally merge it to master.
> Or you want to add separate deployment for the new UI?

Yeah sry, thought this was merged into master 🤦  Approved.

**Pull request merged**
