### PR TITLE
chore(issuer): MythX audit results

### PR DESCRIPTION
**Pull request by josipbagaric**
Adding minor changes to smart contracts after a MythX audit result.

### CODE REVIEW

**Review by kosecki123 — APPROVED** [review]
Is that only issues MythX found?

**Comment by josipbagaric** [comment]
> Is that only issues MythX found?

Yup

**Review by soanvig — APPROVED** [review]

**Comment by soanvig** [comment]
Is it possible to add this to ci so it verifies security on PR?

**Comment by josipbagaric** [comment]
> Is it possible to add this to ci so it verifies security on PR?

Usually yes, but their CLI tool doesn't work with our codebase out-of-the-box. I had to fork their tool and change the source code to make it work. Will open an issue on their repo to fix it and then we can think about adding it to CI.

**Comment by josipbagaric** [comment]
Shouldn't be a huge issue though as the smart contracts will rarely, if ever, change.

**Review by ioncreature — APPROVED** [review]

**Pull request merged**
