### PR TITLE
fix(bugs) add await for function syncCertificationRequestOffChainData

### PR DESCRIPTION
**Pull request by top99963**
This PR solves :
There is no Generation duration data for the last certificate when call getAllCertificates().

### CODE REVIEW

**Comment by JosephBagaric** [comment]
I see that some **tests are failing** - in the `@energyweb/origin` package.

Could you make sure that the tests pass and then request a re-review?
To replicate the failing test locally, run `lerna run --stream --scope @energyweb/origin test:concurrent`.

If you want to make sure that all tests pass, you can run `yarn test` or `yarn test:serial` before commiting the changes.

**Review by josipbagaric — CHANGES_REQUESTED** [review]
I see that some **tests are failing** - in the `@energyweb/origin` package.

Could you make sure that the tests pass and then request a re-review?
To replicate the failing test locally, run `lerna run --stream --scope @energyweb/origin test:concurrent`.

If you want to make sure that all tests pass, you can run `yarn test` or `yarn test:serial` before commiting the changes.

**Review by josipbagaric — APPROVED** [review]

**Comment by josipbagaric** [comment]
@top99963 @Guutong Looks good to me!

You still need to sign our [CLA](https://cla-assistant.io/energywebfoundation/origin?pullRequest=728) before I can merge this.

**Comment by top99963** [comment]
Ok, We’re signed. Thank you for your support.

**Comment by josipbagaric** [comment]
@top99963 @Guutong thanks again for the contribution!

Unfortunately, in the meantime we switched to a new architecture of the code and this has become obsolete.

Will have to close this PR.

**Pull request closed without merging**
