### PR TITLE
Styles inheritance

### PR DESCRIPTION
**Pull request by alexworker23**
This PR provides: 
- Usage of colors extracted from configuration instead of using scss variables
- Unused scss variables removed
- Login page background is added to Context in order to be configurable

### CODE REVIEW

**Comment by kosecki123** [comment]
Would it make sense to scan through commits and try to rebase them? Also, are any of these commits breaking changes?

**Comment by kosecki123** [comment]
Shall we add a wiki page explaining how to use those new variables and what is the outcome?

**Review by kosecki123 — APPROVED** [review]

**Comment by alexworker23** [comment]
> Would it make sense to scan through commits and try to rebase them? Also, are any of these commits breaking changes?

1. Yes 
2. No

**Comment by alexworker23** [comment]
> Shall we add a wiki page explaining how to use those new variables and what is the outcome?

Yes, I think I can document it for comfy usage, and also write the rules how to properly use colors in newly created components, so that we can avoid issues with broken color schemes.

**Comment by kosecki123** [comment]
> > Shall we add a wiki page explaining how to use those new variables and what is the outcome?
> 
> Yes, I think I can document it for comfy usage, and also write the rules how to properly use colors in newly created components, so that we can avoid issues with broken color schemes.

Please add documentation here https://github.com/energywebfoundation/origin/wiki/UI-Customizations

**Comment by kosecki123** [comment]
Looks good now 👍

**Pull request merged**
