### PR TITLE
chore: Remove unused packages from repo

### PR DESCRIPTION
**Pull request by josipbagaric**
Removing unnecessary, outdated and unused packages from the monorepo.

**Removed**
- `@energyweb/device-registry`
- `@energyweb/solar-simulator`
- `@energyweb/migrations`
- `@energyweb/origin-backend-app`
- `@energyweb/origin-device-registry-irec-form-api`

### CODE REVIEW

**Review by ioncreature — APPROVED** [review]

**Review by ioncreature — COMMENTED** [review]
Wait, why do we remove `migrations`, `origin-backend-app`, `origin-device-registry-irec-form-api`?
I thought this is only for `solar-simulator` and `device-registry`

**Comment by josipbagaric** [comment]
> Wait, why do we remove `migrations`, `origin-backend-app`, `origin-device-registry-irec-form-api`?
> I thought this is only for `solar-simulator` and `device-registry`

Are they still needed?

**Comment by ioncreature** [comment]
> Are they still needed?

We use `migrations`, `origin-backend-app`, `origin-device-registry-irec-form-api` on stable deployment at least

**Comment by josipbagaric** [comment]
> > Are they still needed?
> 
> 
> 
> We use `migrations`, `origin-backend-app`, `origin-device-registry-irec-form-api` on stable deployment at least

They will still be there on the release branch for now. Next stable release won't use those packages, but the I-REC ones.

**Pull request closed without merging**
